### ISSUE TITLE
Migrate to null safety

### ISSUE THREAD

**Issue by jigarfumakiya** [radarlabs/flutter-radar#12]
Hello There.

As of now, most of the packages/plugin has been migrated to null-safety, and most of the projects use null safety.
Can you guys please migrate to null safety?
I would be happy to work on PR

Thanks
Jigar

Edit. 1
I see there is PR available to merge for null safety.

Any ETA when you guys can merge it

**Comment by Imperial-lord** [comment]
Same request. We need a null safe version for this.

**Comment by tjulien** [comment]
thanks @jigarfumakiya ! I just applied your work directly into master. Closing this PR.
