### ISSUE TITLE
Install Radar with Kotlin & Swift?

### ISSUE THREAD

**Issue by ibrahimyu** [radarlabs/flutter-radar#15]
New Flutter projects uses Kotlin for Android and Swift for iOS by default, but in Radar's Flutter plugin docs (https://radar.com/documentation/sdk/flutter) the example is still in Java & Objective C. Since most Flutter devs are like me, who have very limited understanding of native platform, it would be very helpful to include steps to install Radar in Kotlin/Swift.

I also noticed that in my Flutter project, the `MainApplication.java` file is missing. No equivalent file in Kotlin either. I have no idea where to put the initialization code for Radar.

Am I missing anything?

**Comment by MartijnAmbagtsheer** [comment]
I'm facing the same issue (even with some experience with native Kotlin/Swift)

**Comment by brettguenther** [comment]
@MartijnAmbagtsheer @ibrahimyu - thanks for flagging. Can you try and create an `Application.kt` like the example below:

```
package <yourPackageName>

import io.flutter.app.FlutterApplication
import io.flutter.embedding.engine.FlutterEngine
import io.flutter.plugin.common.PluginRegistry
import io.flutter.plugins.GeneratedPluginRegistrant
import io.radar.sdk.Radar

class Application : FlutterApplication(), PluginRegistry.PluginRegistrantCallback {

    override fun onCreate() {
        super.onCreate()
        Radar.initialize(this, "<yourPublishableKey>")
    }

    override fun registerWith(registry: PluginRegistry) {
        GeneratedPluginRegistrant.registerWith(FlutterEngine(this))
    }
}
```

Then in your `AndroidManifest.xml` reference the custom application name.

```
 ...
<application
        android:name=".Application"
...
```

Note, if you are only using foreground operations (i.e. Radar search functions) you can also just initialize Radar on the flutter/dart side without any issues.

**Comment by MartijnAmbagtsheer** [comment]
Thanks @brettguenther for your help. 

I've tried your solution, but it begins with that I cannot import the `io.radar.sdk.Radar` class. _See image below_

```e: DIR\android\app\src\main\kotlin\com\example\test\Application.kt: (13, 9): Unresolved reference: Radar```

![image](https://user-images.githubusercontent.com/63644928/215814097-b4f7c323-8e30-447e-8f5d-ef88aeaaca6f.png)

I found out the only thing that actualy has the method `initialize` is `RadarFlutterPlugin`, but the method is private and I think this class is way to far in the structure as needed.

![image](https://user-images.githubusercontent.com/63644928/215814334-de05ee50-f386-406f-a7ea-c060f1da1745.png)

Hope you can help me (and others) further.

PS. Your second solution worked! :-), with the addition that you need to add `await` before calling the function.

**Comment by brettguenther** [comment]
you can add the Radar Android SDK to the `dependencies` section of your Android app's `build.gradle` file. example below 

```dependencies {
    ...
    implementation 'io.radar:sdk:3.5.9'
}```
